global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: spring-webflux-metrics-localhost
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - '192.168.1.3:8080'